### ISSUE TITLE
feat: use default report name

### ISSUE THREAD

**Issue by afdesk** [afdesk/scan2html#21]
we need to have a default report name (eg `result.html`)

**Comment by nikpivkin** [comment]
@afdesk after the [commit](https://github.com/afdesk/scan2html/commit/6865af8e890c10f05058c088d2b99b9b994badc8), the arguments are passed to trivy as follows: the first argument is passed as a command, the last as a file name, and the rest as is. Therefore, we cannot accurately track whether the file name was passed.

for example:
```shell
trivy scan2html aws report_name.html
trivy scan2html image {image_name} report_name.html
```

Is it still required?

**Comment by afdesk** [comment]
good catch. closed.
