### ISSUE TITLE
plugin error no such file or directory

### ISSUE THREAD

**Issue by DenMX** [afdesk/scan2html#56]
When i call "trivy scan2html -h" i got an error that says no such file or directory, but file exist. Mb i'm doing something wrong
![image](https://github.com/afdesk/scan2html/assets/69713078/ae6c8916-b74c-43c2-b2a4-611e4d67fae4)

**Comment by nikpivkin** [comment]
Hi @DenMX !

How did you install the plugin and what OS do you have?

**Comment by DenMX** [comment]
I'm sorry. I confused repositories)) This plugin works fine!

**Comment by DenMX** [comment]
I'm sorry. I confused repositories)) This plugin works fine!
